user_project/user_app/urls.py
from django.urls import path
from .import views

# template urls
app_name = 'user_app'

urlpatterns = [
    path('user_login/', views.user_login, name='user_login'),
    path('register/', views.register, name='register')
]

user_project/user_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from user_app import views

urlpatterns = [
    path("", views.index, name='index'),
    path('admin/', admin.site.urls),
    path('user_app/', include("user_app.urls")),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special')
]

user_project/user_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='user_app/profile_pics', blank=True)

    def __str__(self):
        return self.user.username

user_project/user_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

user_project/user_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm

# LOGIN IMPORTS
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    return render(request, 'user_app/index.html')


@login_required()
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required()
def special(request):
    return HttpResponse('You are logged in, Nice!')


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            # save the user form to database
            user = user_form.save()
            # Hash the password
            user.set_password(user.password)
            # update the hashed password
            user.save()

            # Now deal with extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)
            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                # if yes then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']
                # Now save model
            profile.save()
            # Registration successful
            registered = True

        else:
            # if one of the form is invalid else get called
            print(user_form.errors, profile_form.errors)
    else:
        # Was not a HTTP Post so we render the forms as blank
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feedback
    # to the register.html page

    return render(request, 'user_app/register.html', {'user_form': user_form,
                                                      'profile_form': profile_form,
                                                      'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE!')
        else:
            print("Someone tried to login and failed!")
            print('username: {} and password {}'.format(username, password))
            return HttpResponse('Invalid login details supplied!')
    else:
        return render(request, 'user_app/login.html', {})

user_project/templates/user_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
                <li><a class="nav-tem nav-link" href="{% url 'admin:index' %}">ADMIN</a></li>
                <li><a class="nav-item nav-link" href="{% url 'user_app:register'%}">REGISTER</a></li>

                {% if user.is_authenticated %}
                    <li><a class="nav-item nav-link" href="{% url 'logout' %}">LOG-OUT</a></li>
                {% else %}
                    <li><a class="nav-item nav-link" href="{% url 'user_app:user_login' %}">LOG-IN</a></li>
                {% endif %}


            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>

</body>
</html>

user_project/templates/user_app/index.html
{% extends "user_app/base.html" %}
{% block body_block %}
    <div class="container">
        <div class="jumbotron">
            <hi>Welcome To DJango!</hi>
        </div>
    </div>
{% endblock %}

user_project/templates/user_app/login.html
{% extends 'user_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Log-in</h1>
    <form action="{% url 'user_app:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input name="username" type="text" placeholder="Enter Username">

        <label for="password">Password</label>
        <input name="password" type="password" >

        <input type="submit" value="LOGIN">
    </form>
</div>

{% endblock %}

user_project/templates/user_app/register.html
{% extends "user_app/base.html" %}
{% load static %}
{% block body_block %}
    <div class="container">
        <div class="jumbotron">
            {% if registered %}
                <h1>Thank you for registering!</h1>
            {% else %}
                <h1>Register Here</h1>
                <h3>Just fill out the form.</h3>
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" value="Register">
            </form>
            {% endif %}
        </div>
    </div>
{% endblock %}